// Types for the monthly recap feature

export type EffortScores = {
  practiceSessions: number;
  mentalGame: number;
  strengthTraining: number;
  mobilityExercises: number;
  fullSwingWork: number;
  shortGameWork: number;
  puttingWork: number;
};

export type EffortCategory = {
  id: keyof EffortScores;
  label: string;
  description: string;
};

export type MonthlyRecap = {
  id: string;
  userId: string;
  month: string; // YYYY-MM format
  handicapStartOfMonth: number;
  handicapEndOfMonth: number;
  effortScores: EffortScores;
  notes?: string;
  createdAt: Date;
  autoGenerated?: boolean;
  userReviewed?: boolean;
  autoSuggestedScores?: Partial<EffortScores>;
};

export const effortCategories: EffortCategory[] = [
  { id: "practiceSessions", label: "Practice Sessions", description: "How consistently did you practice? (frequency & quality)" },
  { id: "mentalGame", label: "Mental Game", description: "Did you regularly work on mental strategies (visualization, routine)?" },
  { id: "strengthTraining", label: "Strength Training", description: "How frequently did you incorporate strength work?" },
  { id: "mobilityExercises", label: "Mobility Exercises", description: "How consistently did you perform mobility drills?" },
  { id: "fullSwingWork", label: "Full-swing Work", description: "Did you put focused effort into full-swing improvement?" },
  { id: "shortGameWork", label: "Short Game Work", description: "How consistently did you practice short-game techniques (chipping/pitching)?" },
  { id: "puttingWork", label: "Putting Work", description: "Did you regularly and intentionally practice putting?" }
]; 